name = "first"
description = ""
version = "0.1.0-dev"

authors = ["Nicu Popescu"]
maintainers = ["Nicu Popescu <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []
